// House of Jewelux - Global Data & Inventory Catalogue V2
// Master Build: Fine 925 Sterling Silver Focus, Future Gold Suite, Studio Persistence & Multilingual Dictionaries

const JEWELUX_DATA = {
  storeConfig: {
    whatsappNumber: "+916377061020",
    whatsappWelcome: "Hello House of Jewelux Concierge! I would like to inquire about fine jewellery and bespoke commissions.",
    founderName: "Yuvraj Soni",
    founderTitle: "Founder & Creative Director",
    founderPIN: "1985",
    announcementText: "THE SILVER EDIT 2026 — Certified 925 Hallmarked Fine Silver & Anti-Tarnish Rhodium • Complimentary Insured Global Delivery",
    heroHeadline: "Where Elegance Becomes Eternal",
    heroSubtitle: "Italian Didone sophistication sculpted with generational Indian artistry. Discover certified 925 fine sterling silver and bespoke gold bridal commissions.",
    heroCtaText: "Explore The Silver Edit",
    heroCtaHash: "#silver",
    freeShippingThresholdUSD: 250,
    shippingDaysDomestic: "2 - 4 Business Days (Armored White-Glove)",
    shippingDaysInternational: "4 - 7 Business Days (Fully Insured FedEx Priority)",
    returnsGuaranteeDays: 30,
    silverSpotlightEnabled: true
  },

  currencies: {
    USD: { symbol: '$', rate: 1.0, label: 'USD ($)' },
    EUR: { symbol: '€', rate: 0.92, label: 'EUR (€)' },
    GBP: { symbol: '£', rate: 0.79, label: 'GBP (£)' },
    INR: { symbol: '₹', rate: 83.5, label: 'INR (₹)' },
    AED: { symbol: 'AED ', rate: 3.67, label: 'AED (د.إ)' }
  },

                                categories: [
    { id: 'all', name: 'All Masterpieces', hash: '#shop', url: '/shop' },
    { id: 'rings', name: 'Rings', hash: '#rings', url: '/shop/rings' },
    { id: 'earrings', name: 'Earrings', hash: '#earrings', url: '/shop/earrings' },
    { id: 'bracelets', name: 'Bracelets', hash: '#bracelets', url: '/shop/bracelets' },
    { id: 'necklaces', name: 'Necklaces', hash: '#necklaces', url: '/shop/necklaces' },
    { id: 'brooches', name: 'Brooches', hash: '#brooches', url: '/shop/brooches' }
  ],

  collections: [
    {
      id: 'silver-edit',
      name: 'The Silver Edit',
      tagline: 'Certified 925 Sterling Silver dipped in liquid platinum-rhodium lustre.',
      image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85',
      category: 'silver',
      description: 'Modern architectural silhouettes set with brilliant lab-certified GRA moissanite and micro-pavé diamond accents. 100% anti-tarnish and skin-safe.'
    },
    {
      id: 'eternal-couples',
      name: 'Newlywed & Couple Sanctuary',
      tagline: 'Conceived for love, sculpted for lifelong companionship.',
      image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85',
      category: 'couples',
      description: 'Ergonomic comfort-fit couple bands, bridal promise solitaires, and sacred modern mangalsutra necklaces crafted in 925 hallmarked sterling silver.'
    },
    {
      id: 'everyday-icons',
      name: 'The Everyday Icons',
      tagline: 'Understated elegance designed to elevate personal daily rituals.',
      image: 'https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85',
      category: 'bracelets',
      description: 'Articulated tennis bracelets, stackable cuffs, and luminous solitaire drops engineered for seamless transitions from office to evening gala.'
    },
    {
      id: 'temple-heritage',
      name: 'The Temple Collection',
      tagline: 'Sacred Indian artisanal heritage harmonized with contemporary Italian grace.',
      image: 'images/jewelux_temple_heritage.jpg',
      category: 'temple',
      description: 'Hand-chased 22K antique matte gold, uncut polki diamonds, and divine sacred motifs reimagined for the international aesthete.'
    },
    {
      id: 'gold-vault',
      name: 'The Royal Gold Vault',
      tagline: 'Haute joaillerie and high-carat gold pieces crafted on bespoke commission.',
      image: 'images/jewelux_hero_necklace.jpg',
      category: 'gold-vault',
      description: 'Solid 18K Fairmined Champagne Gold and D-Flawless natural diamonds created exclusively on private salon commission.'
    }
  ],

  products: [
    {
        "id": "HJ-RNG-001",
        "name": "The Celestial Radiance 925 Solitaire Ring",
        "category": "rings",
        "collection": "silver-edit",
        "tag": "Silver Flagship",
        "priceUSD": 185,
        "image": "images/jewelux_solitaire_ring.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver (Anti-Tarnish Rhodium)",
        "stone": "2.5ct Certified Lab Moissanite (D-Flawless)",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Hearts & Arrows Ideal Brilliant",
        "clarity": "VVS1 Laboratory Certified",
        "dimensions": "8.5mm Center Stone \u2022 2.0mm Pav\u00e9 Band",
        "certificate": "GRA / GIA Dossier Registered",
        "description": "Architectural 6-prong crown setting cradling a radiant 2.5-carat lab-grown moissanite. Dipped in liquid rhodium for lifelong anti-tarnish luster.",
        "badge": "Bestseller",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Couples"
    },
    {
        "id": "HJ-RNG-002",
        "name": "The Amore Eternity Couple Bands (Pair)",
        "category": "rings",
        "collection": "eternal-couples",
        "tag": "Couple Sanctuary",
        "priceUSD": 240,
        "image": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver & Liquid Rhodium",
        "stone": "Micro-Pav\u00e9 Conflict-Free Lab Diamonds",
        "purity": "Stamped 925 Silver",
        "cut": "Round Brilliant Pav\u00e9",
        "clarity": "VVS1 Eye-Clean",
        "dimensions": "His: 5.0mm Brushed Band \u2022 Hers: 3.2mm Pav\u00e9 Band",
        "certificate": "Jewelux Atelier Authenticity Dossier",
        "description": "Designed for lifelong companionship. His band features brushed rhodium satin with beveled comfort-fit edges; hers glistens with a continuous channel of micro-pav\u00e9 diamonds.",
        "badge": "Bridal Favorite",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Newlywed Couples"
    },
    {
        "id": "HJ-RNG-003",
        "name": "The Empress Emerald-Cut Halo Ring",
        "category": "rings",
        "collection": "silver-edit",
        "tag": "Art Deco Atelier",
        "priceUSD": 220,
        "image": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver (Platinum Finish)",
        "stone": "3.0ct Emerald-Cut Moissanite with French Pav\u00e9 Halo",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Step-Cut Emerald Facet",
        "clarity": "FL / VVS1 Flawless",
        "dimensions": "9x7mm Center Stone \u2022 1.8mm Halo Rim",
        "certificate": "GRA Laboratory Certified",
        "description": "Inspired by 1930s Milanese aristocracy, step-cut facets generate hypnotic hall-of-mirrors light dispersion encircled by a delicate French pav\u00e9 border.",
        "badge": "Limited Edition",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Modern Brides"
    },
    {
        "id": "HJ-RNG-004",
        "name": "The Royal Marquise Diamond Pavilion Ring",
        "category": "rings",
        "collection": "gold-vault",
        "tag": "Bespoke Joaillerie",
        "priceUSD": 580,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Champagne Gold Vermeil & 925 Silver Core",
        "stone": "2.2ct Marquise Cut Lab Diamond",
        "purity": "18K Gold Plated 925 Hallmarked",
        "cut": "Marquise Modified Brilliant",
        "clarity": "VVS1 D-Color",
        "dimensions": "12x6mm Center Stone",
        "certificate": "GIA Dossier Certified",
        "description": "An elongated marquise silhouette that flatters the finger with graceful symmetry, finished in warm Florentine champagne gold.",
        "badge": "Atelier Spotlight",
        "isSilver": true,
        "isGold": true,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Discerning Women"
    },
    {
        "id": "HJ-RNG-005",
        "name": "The Verona Pav\u00e9 Crisscross Band",
        "category": "rings",
        "collection": "silver-edit",
        "tag": "Modern Architectural",
        "priceUSD": 165,
        "image": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver (Anti-Tarnish Rhodium)",
        "stone": "Dual Ribbon Micro-Pav\u00e9 Moissanites",
        "purity": "Stamped 925",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "4.5mm Tapered Width",
        "certificate": "Jewelux Assurance Card",
        "description": "Interlocking sculptural bands symbolizing intertwined journeys. Flawless micro-pav\u00e9 gems reflect radiant ambient luminescence.",
        "badge": "Everyday Luxury",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-RNG-006",
        "name": "The Venetian Oval Luminary Solitaire",
        "category": "rings",
        "collection": "silver-edit",
        "tag": "Bridal Promise",
        "priceUSD": 195,
        "image": "images/jewelux_solitaire_ring.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Fine Sterling Silver",
        "stone": "2.0ct Oval Brilliant Moissanite",
        "purity": "925 Stamped & Rhodium Dipped",
        "cut": "Oval Brilliant Facet",
        "clarity": "VVS1 Flawless",
        "dimensions": "10x7mm Oval Center",
        "certificate": "GRA Registered Lab Dossier",
        "description": "A graceful oval brilliant gemstone held in an understated 4-prong low-profile cradle, engineered for effortless daily comfort.",
        "badge": "New Arrival",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Couples"
    },
    {
        "id": "HJ-RNG-007",
        "name": "The Sovereign Signet Promise Band",
        "category": "rings",
        "collection": "eternal-couples",
        "tag": "Heirloom Signet",
        "priceUSD": 175,
        "image": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "Brushed & Polished 925 Sterling Silver",
        "stone": "Center Flush-Set Baguette Diamond Accent",
        "purity": "Solid 925 Silver",
        "cut": "Step Cut Baguette",
        "clarity": "VS1",
        "dimensions": "6.0mm Face Width",
        "certificate": "Jewelux Atelier Seal",
        "description": "Subtle minimalism with substantial weight. Features a satin-brushed face with mirror-polished inner shank.",
        "badge": "Unisex Icon",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Men & Women"
    },
    {
        "id": "HJ-RNG-008",
        "name": "The Florence Pear Teardrop Solitaire",
        "category": "rings",
        "collection": "silver-edit",
        "tag": "Haute Teardrop",
        "priceUSD": 210,
        "image": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Silver Plated in Liquid Rose Gold",
        "stone": "1.8ct Pear Cut Lab Diamond",
        "purity": "925 Hallmarked",
        "cut": "Pear Modified Brilliant",
        "clarity": "VVS1",
        "dimensions": "9x6mm Pear Stone",
        "certificate": "GRA Laboratory Certified",
        "description": "Sensuous teardrop shape capturing feminine grace, set on a whispered knife-edge shank finished in romantic rose gold.",
        "badge": "Romantic Edit",
        "isSilver": true,
        "isGold": true,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-RNG-009",
        "name": "The Eternal Vow Dual Contour Band",
        "category": "rings",
        "collection": "eternal-couples",
        "tag": "Bridal Contoured",
        "priceUSD": 150,
        "image": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Fine Sterling Silver",
        "stone": "Pav\u00e9 Diamond Accent V-Curve",
        "purity": "Stamped 925",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "2.2mm Contoured Ribbon",
        "certificate": "Jewelux Certificate",
        "description": "Articulated gently in a delicate chevron contour designed to sit flush against any solitaire or promise ring.",
        "badge": "Bridal Essential",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Brides & Newlyweds"
    },
    {
        "id": "HJ-RNG-010",
        "name": "The Starlight Triple Pav\u00e9 Eternity Ring",
        "category": "rings",
        "collection": "silver-edit",
        "tag": "Eternity Statement",
        "priceUSD": 230,
        "image": "images/jewelux_solitaire_ring.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver (Heavy Rhodium Coating)",
        "stone": "3 Rows of Flawless Lab Moissanites",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Round Brilliant Micro-Pav\u00e9",
        "clarity": "VVS1",
        "dimensions": "4.8mm Full Eternity Band",
        "certificate": "GRA Certified Full Band",
        "description": "Over 70 handset laboratory moissanites arranged in three luminous tiers, radiating uninterrupted fire from every viewing angle.",
        "badge": "High Sparkle",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Anniversaries"
    },
    {
        "id": "HJ-EAR-001",
        "name": "The Lumina Teardrop Solitaire Earrings",
        "category": "earrings",
        "collection": "silver-edit",
        "tag": "Drop Solitaire",
        "priceUSD": 175,
        "image": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver (Anti-Tarnish Rhodium)",
        "stone": "2.0ct Each Certified Pear Moissanites",
        "purity": "Stamped 925",
        "cut": "Pear Brilliant",
        "clarity": "VVS1 Laboratory Certified",
        "dimensions": "18mm Total Drop \u2022 7x5mm Center Gems",
        "certificate": "GRA Certified Pair",
        "description": "Suspended from delicate pav\u00e9 studs, these faceted teardrops catch ambient twilight, swaying effortlessly with every step.",
        "badge": "Bestseller",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-EAR-002",
        "name": "The Milanese Pav\u00e9 Huggie Hoops",
        "category": "earrings",
        "collection": "everyday-icons",
        "tag": "Everyday Icon",
        "priceUSD": 140,
        "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Champagne Gold Finish & 925 Silver",
        "stone": "Dual-Row Micro-Pav\u00e9 Diamonds",
        "purity": "925 Hallmarked",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "12mm Diameter \u2022 2.5mm Width",
        "certificate": "Jewelux Atelier Dossier",
        "description": "Ergonomic click-latch closure huggies sculpted for daily wear. Seamless comfort whether seated in boardrooms or dining in Venice.",
        "badge": "Essential",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Modern Women"
    },
    {
        "id": "HJ-EAR-003",
        "name": "The Cascade Chandelier Diamond Drops",
        "category": "earrings",
        "collection": "silver-edit",
        "tag": "Gala Chandelier",
        "priceUSD": 290,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver (Platinum Sheen)",
        "stone": "Graduated Moissanite Drops & Marquis Links",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Round & Marquise Brilliant",
        "clarity": "VVS1",
        "dimensions": "52mm Dramatic Drop",
        "certificate": "GRA Laboratory Certificate",
        "description": "Dramatic articulated chandeliers engineered to dance with candlelight. Feather-light balance prevents earlobe fatigue.",
        "badge": "Red Carpet Edit",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Evening Gala & Brides"
    },
    {
        "id": "HJ-EAR-004",
        "name": "The Royal Colombian Emerald Halo Studs",
        "category": "earrings",
        "collection": "gold-vault",
        "tag": "Haute Emerald",
        "priceUSD": 380,
        "image": "images/jewelux_hero_necklace.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Florentine Champagne Gold Vermeil",
        "stone": "Lab-Grown Colombian Emeralds with Diamond Halos",
        "purity": "18K Gold over 925 Silver",
        "cut": "Octagonal Step Cut",
        "clarity": "VVS Vivid Green",
        "dimensions": "8x6mm Emerald Center",
        "certificate": "GIA Certified Gemological Dossier",
        "description": "Vivid deep verdant emeralds encircled by sixteen micro-pav\u00e9 halos. An opulent tribute to classic royal European dynasty jewels.",
        "badge": "Atelier Masterpiece",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Discerning Women"
    },
    {
        "id": "HJ-EAR-005",
        "name": "The Starlight 4-Claw Solitaire Studs",
        "category": "earrings",
        "collection": "silver-edit",
        "tag": "Daily Classic",
        "priceUSD": 130,
        "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver with Rhodium Dipping",
        "stone": "1.5ct Each D-Flawless Moissanite",
        "purity": "Stamped 925",
        "cut": "Hearts & Arrows Round Ideal",
        "clarity": "VVS1",
        "dimensions": "7.5mm Diameter",
        "certificate": "GRA Card Verification",
        "description": "The quintessential diamond studs. Minimalist four-claw architecture maximizes light transmission through the pavilion facets.",
        "badge": "Timeless",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-EAR-006",
        "name": "The Roman Arc Architectural Ear Cuffs",
        "category": "earrings",
        "collection": "everyday-icons",
        "tag": "Sculptural Cuff",
        "priceUSD": 155,
        "image": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        "metal": "Solid 925 Sterling Silver",
        "stone": "Pav\u00e9 Ribbons on Inner Flange",
        "purity": "925 Stamped",
        "cut": "Micro Brilliant",
        "clarity": "VVS1",
        "dimensions": "20mm Curvature",
        "certificate": "Jewelux Atelier Guarantee",
        "description": "Sweeping curved silhouette that hugs the ear cartilage without requiring piercing. Modern Roman minimalism at its finest.",
        "badge": "Editorial Pick",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Fashion Leaders"
    },
    {
        "id": "HJ-EAR-007",
        "name": "The Bellini South Sea Pearl Drops",
        "category": "earrings",
        "collection": "gold-vault",
        "tag": "Pearl Heirlooms",
        "priceUSD": 275,
        "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Champagne Gold & 925 Silver",
        "stone": "11mm Luminous South Sea Pearl Drops",
        "purity": "18K Gold Plated 925",
        "cut": "Natural Spheroid Pearl",
        "clarity": "AAA High Luster",
        "dimensions": "11mm Pearl \u2022 28mm Full Drop",
        "certificate": "Pearl Authenticity Dossier",
        "description": "Silken, unblemished luster pearls suspended below champagne gold diamond-set ribbons. Soft, warm vanilla luminescence.",
        "badge": "Bridal Luxury",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Brides & Elegance Lovers"
    },
    {
        "id": "HJ-EAR-008",
        "name": "The Celestial Starburst Pav\u00e9 Drops",
        "category": "earrings",
        "collection": "silver-edit",
        "tag": "Starlight Collection",
        "priceUSD": 195,
        "image": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver & Platinum Sheen",
        "stone": "Pav\u00e9 Diamond Multi-Ray Starburst",
        "purity": "925 Hallmarked",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "25mm Drop",
        "certificate": "GRA Verification",
        "description": "Scintillating eight-pointed northern stars cascading from delicate pav\u00e9 studs, echoing the eternal nocturnal heavens.",
        "badge": "Signature",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-EAR-009",
        "name": "The Deco Geometric Baguette Dangles",
        "category": "earrings",
        "collection": "silver-edit",
        "tag": "Art Deco",
        "priceUSD": 220,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver",
        "stone": "Step-Cut Baguettes & Triangle Facets",
        "purity": "Stamped 925",
        "cut": "Baguette Step Cut",
        "clarity": "VVS1",
        "dimensions": "34mm Linear Drop",
        "certificate": "Jewelux Dossier",
        "description": "Crisp geometric lines reminiscent of Milanese architectural arches, balancing razor-sharp modernism with haute joaillerie sparkle.",
        "badge": "Modern Couture",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-EAR-010",
        "name": "The Sovereign Bridal Jhumka Drops",
        "category": "earrings",
        "collection": "temple-heritage",
        "tag": "Temple Grandeur",
        "priceUSD": 310,
        "image": "images/jewelux_temple_heritage.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "metal": "22K Antique Gold Wash over 925 Silver",
        "stone": "Uncut Polki Moissanites & Seed Pearls",
        "purity": "925 Core with 22K Gold Finish",
        "cut": "Traditional Polki Flat Slice",
        "clarity": "Authentic Antique Cut",
        "dimensions": "42mm Bell Drop",
        "certificate": "Heritage Atelier Dossier",
        "description": "Reinvented temple bell jhumkas with suspended pearl fringe, echoing centuries of divine Indian wedding celebrations.",
        "badge": "Heritage Bride",
        "isSilver": true,
        "isGold": true,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Bridal & Festive"
    },
    {
        "id": "HJ-BRC-001",
        "name": "The Riviera 4mm Tennis Bracelet",
        "category": "bracelets",
        "collection": "silver-edit",
        "tag": "Tennis Masterpiece",
        "priceUSD": 260,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver (Anti-Tarnish Rhodium)",
        "stone": "58 Individually Set Lab Moissanites (4mm)",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Hearts & Arrows Round Ideal",
        "clarity": "VVS1 D-Flawless",
        "dimensions": "7.0 inches \u2022 Double-Safety Clasp",
        "certificate": "Full Line GRA Laboratory Dossier",
        "description": "Continuous line of pure light. Hand-articulated four-prong link segments flex naturally with the wrist; dual-safety box clasp ensures lifetime security.",
        "badge": "Bestseller",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Gift Giving"
    },
    {
        "id": "HJ-BRC-002",
        "name": "The Milanese Sculpted Torque Cuff",
        "category": "bracelets",
        "collection": "silver-edit",
        "tag": "Sculptural Silver",
        "priceUSD": 210,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_editorial_hero.jpg",
        "metal": "Solid 925 Fine Sterling Silver",
        "stone": "Twin Pav\u00e9 Finials with Moissanite Accents",
        "purity": "Heavyweight 925 Silver (32 Grams)",
        "cut": "Micro-Pav\u00e9 Terminals",
        "clarity": "VVS1",
        "dimensions": "62mm Internal Diameter (Malleable Fit)",
        "certificate": "Jewelux Assay Office Hallmark",
        "description": "Heavyweight solid silver torc cuff hand-shaped by Milanese silversmiths. Features a smooth mirror-burnished body ending in faceted diamond finials.",
        "badge": "Statement Icon",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Minimalist Women"
    },
    {
        "id": "HJ-BRC-003",
        "name": "The Royal Baguette Bar Link Bracelet",
        "category": "bracelets",
        "collection": "gold-vault",
        "tag": "Bespoke Links",
        "priceUSD": 340,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Champagne Gold Finish & 925 Silver",
        "stone": "Alternating Channel Baguette Diamonds",
        "purity": "18K Gold Plated 925",
        "cut": "Precision Step-Cut Baguettes",
        "clarity": "VVS1",
        "dimensions": "7.2 inches \u2022 3.8mm Width",
        "certificate": "GIA Certified Stone Selection",
        "description": "Architectural link bars inset with channel-set baguette gemstones. Warm Florentine champagne gold finish reflects opulent evening grandeur.",
        "badge": "Luxury Link",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-BRC-004",
        "name": "The Eternal Knot Bridal Charm Bracelet",
        "category": "bracelets",
        "collection": "eternal-couples",
        "tag": "Bridal Sanctuary",
        "priceUSD": 190,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver with Rhodium Dipping",
        "stone": "Pav\u00e9 Set Interlocking Lovers Knot Charm",
        "purity": "Stamped 925",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "Adjustable 6.5 to 7.5 inches",
        "certificate": "Jewelux Bridal Certificate",
        "description": "An unbroken knot sculpted in gleaming silver, celebrating everlasting marital devotion. Includes an adjustable extension chain.",
        "badge": "Newlywed Favorite",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Brides & Newlyweds"
    },
    {
        "id": "HJ-BRC-005",
        "name": "The Pav\u00e9 Diamond Station Cable Chain",
        "category": "bracelets",
        "collection": "everyday-icons",
        "tag": "Everyday Delicate",
        "priceUSD": 145,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver",
        "stone": "5 Bezel-Set Solitaire Stations",
        "purity": "925 Hallmarked",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "6.8 inches + 1 inch Extender",
        "certificate": "Jewelux Authenticity Dossier",
        "description": "Five shimmering bezel-set diamond stations spaced symmetrically along a feather-light diamond-cut cable chain.",
        "badge": "Stacking Essential",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-BRC-006",
        "name": "The Verona Florentine Mesh Ribbon Bracelet",
        "category": "bracelets",
        "collection": "gold-vault",
        "tag": "Mesh Joaillerie",
        "priceUSD": 295,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_editorial_hero.jpg",
        "metal": "18K Champagne Gold Vermeil & 925 Silver",
        "stone": "Pav\u00e9 Diamond Bar Centerpiece",
        "purity": "18K Vermeil Stamped 925",
        "cut": "Pav\u00e9 Setting",
        "clarity": "VVS1",
        "dimensions": "8mm Flexible Mesh Band",
        "certificate": "Jewelux Atelier Assurance",
        "description": "Woven with the fluidity of silken fabric, this Milanese mesh band contours smoothly to the wrist with an opulent magnetic buckle.",
        "badge": "New Arrival",
        "isSilver": true,
        "isGold": true,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-BRC-007",
        "name": "The Emerald Solitaire Station Chain Bracelet",
        "category": "bracelets",
        "collection": "silver-edit",
        "tag": "Verdant Pop",
        "priceUSD": 175,
        "image": "images/jewelux_hero_necklace.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver (Platinum Sheen)",
        "stone": "1.2ct Vivid Green Lab Colombian Emerald",
        "purity": "Stamped 925",
        "cut": "Emerald Step Cut",
        "clarity": "Eye-Clean Vivid",
        "dimensions": "7x5mm Center Stone",
        "certificate": "GRA Gemstone Verification",
        "description": "A single hypnotic green emerald suspended on an ultra-fine platinum-finished sterling silver trace chain.",
        "badge": "Color Accent",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-BRC-008",
        "name": "The Dual Contour Couple Cuff (His & Hers)",
        "category": "bracelets",
        "collection": "eternal-couples",
        "tag": "Couple Cuff Pair",
        "priceUSD": 270,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Solid Sterling Silver (Brushed & Polished)",
        "stone": "Flush-Set Solitaire Diamond on Hers",
        "purity": "Stamped 925",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "His: 8mm Cuff \u2022 Hers: 5mm Cuff",
        "certificate": "Couple Keepsake Dossier",
        "description": "Matching cuff pair with internal engraved covenant coordinates. Subtle exterior geometry designed for modern lovers.",
        "badge": "Couples Pair",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Newlywed Couples"
    },
    {
        "id": "HJ-BRC-009",
        "name": "The Sovereign Herringbone Liquid Metal Ribbon",
        "category": "bracelets",
        "collection": "silver-edit",
        "tag": "Liquid Silver",
        "priceUSD": 160,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver Plated in Liquid Rhodium",
        "stone": "Mirror-Faceted Solid Links",
        "purity": "Solid 925",
        "cut": "Diamond-Cut Beveled Edges",
        "clarity": "Mirror Luster",
        "dimensions": "5.5mm Width \u2022 7.0 inches",
        "certificate": "Jewelux Hallmark",
        "description": "Fluid herringbone ribbon links that drape across the wrist like liquid chrome, catching every subtle shift of ambient lighting.",
        "badge": "Sleek Modern",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-BRC-010",
        "name": "The Celestial Orbit Double Wrap Pav\u00e9 Bracelet",
        "category": "bracelets",
        "collection": "silver-edit",
        "tag": "Orbit Double Wrap",
        "priceUSD": 225,
        "image": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver & Platinum Sheen",
        "stone": "Twin Orbit Rings with Micro-Pav\u00e9 Diamonds",
        "purity": "925 Stamped",
        "cut": "Micro Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "Adjustable Double Wrap",
        "certificate": "Jewelux Authenticity Dossier",
        "description": "Double-wrapping fine snake chain held by an interlocking pav\u00e9 celestial orbit ring. Modern European layering at its finest.",
        "badge": "Chic Layering",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-NCK-001",
        "name": "The Luna Pav\u00e9 Halo Bridal Mangalsutra",
        "category": "necklaces",
        "collection": "eternal-couples",
        "tag": "Modern Mangalsutra",
        "priceUSD": 280,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_hero_necklace.jpg",
        "metal": "925 Sterling Silver & Liquid Rhodium",
        "stone": "1.5ct Solitaire with Double Pav\u00e9 Halo & Black Spinel Beads",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Round Brilliant Hearts & Arrows",
        "clarity": "VVS1 Flawless",
        "dimensions": "16-18 inch Adjustable Chain \u2022 12mm Pendant",
        "certificate": "GRA Laboratory Certified",
        "description": "Reinventing sacred matrimony for the modern Indian woman. Natural faceted black spinel beads integrated into a feather-light rhodium chain with a solitaire diamond halo centerpiece.",
        "badge": "Bridal Spotlight",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Modern Brides"
    },
    {
        "id": "HJ-NCK-002",
        "name": "The Empress Emerald & Diamond Regal Choker",
        "category": "necklaces",
        "collection": "gold-vault",
        "tag": "Haute Joaillerie",
        "priceUSD": 1250,
        "image": "images/jewelux_hero_necklace.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Champagne Gold & 925 Silver Base",
        "stone": "18.5 carats Certified Colombian Emeralds & D-Flawless Moissanite",
        "purity": "18K Gold Vermeil Stamped",
        "cut": "Step Cut Octagonal & Marquis",
        "clarity": "VVS Royal Green",
        "dimensions": "15.5 inch Articulated Choker",
        "certificate": "GIA Dossier Certified",
        "description": "Our atelier masterpiece. Cascading vibrant verdant emeralds accented by pear-cut lab diamonds. Delivered in handcrafted velvet archival trunk.",
        "badge": "Masterpiece",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "High Jewelry Patrons"
    },
    {
        "id": "HJ-NCK-003",
        "name": "The Solitaire Floating Illusion Pendant",
        "category": "necklaces",
        "collection": "silver-edit",
        "tag": "Floating Diamond",
        "priceUSD": 165,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver with Liquid Rhodium",
        "stone": "1.5ct Round Brilliant Lab Moissanite",
        "purity": "Stamped 925",
        "cut": "Hearts & Arrows Round Ideal",
        "clarity": "VVS1",
        "dimensions": "7.5mm Floating Bezel \u2022 16-18 inch Chain",
        "certificate": "GRA Registration Dossier",
        "description": "Minimally held in an invisible floating bezel setting that allows light to pour through the girdle from all 360 degrees.",
        "badge": "Everyday Icon",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-NCK-004",
        "name": "The Sacred Heritage Temple Locket Necklace",
        "category": "necklaces",
        "collection": "temple-heritage",
        "tag": "Temple Heritage",
        "priceUSD": 450,
        "image": "images/jewelux_temple_heritage.jpg",
        "hoverImage": "images/jewelux_hero_necklace.jpg",
        "metal": "22K Antique Matte Gold Finish & 925 Core",
        "stone": "Uncut Polki Moissanites & Basra Pearl Cluster",
        "purity": "22K Gold Finish on 925 Silver",
        "cut": "Polki Flat Cut",
        "clarity": "Authentic Heritage Finish",
        "dimensions": "32mm Hand-Chased Locket Pendant",
        "certificate": "Heritage Atelier Dossier",
        "description": "Hand-engraved sacred floral mandala locket opening to hold personal memories or vows, suspended from a hand-twisted gold rope chain.",
        "badge": "Heirloom Edition",
        "isSilver": true,
        "isGold": true,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Connoisseurs & Brides"
    },
    {
        "id": "HJ-NCK-005",
        "name": "The Riviera Diamond Tennis Collar",
        "category": "necklaces",
        "collection": "silver-edit",
        "tag": "Tennis Collar",
        "priceUSD": 520,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1611591475877-2287e0766324?auto=format&fit=crop&w=1000&q=85",
        "metal": "Solid 925 Sterling Silver (Rhodium Dipped)",
        "stone": "Graduated 3mm to 6mm Lab Moissanites",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "16 inches Graduated Line Collar",
        "certificate": "Full Line GRA Laboratory Dossier",
        "description": "A full 16-inch continuous river of fire. Stones graduate subtly toward a breathtaking 6mm center gem resting on the collarbone.",
        "badge": "Gala Statement",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-NCK-006",
        "name": "The Venetian Lariat Y-Drop Pav\u00e9 Chain",
        "category": "necklaces",
        "collection": "silver-edit",
        "tag": "Lariat Silhouette",
        "priceUSD": 195,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver",
        "stone": "Pav\u00e9 Slider Ring with Pear Moissanite Drop",
        "purity": "Stamped 925",
        "cut": "Pear & Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "20 inch Chain \u2022 Adjustable Y-Drop Length",
        "certificate": "Jewelux Dossier",
        "description": "Adjustable pav\u00e9 slide mechanism transforms this necklace from a high choker to a plunging d\u00e9colletage accent in seconds.",
        "badge": "Versatile Glamour",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Modern Women"
    },
    {
        "id": "HJ-NCK-007",
        "name": "The Celestial Star Constellation Pendant",
        "category": "necklaces",
        "collection": "silver-edit",
        "tag": "Zodiac Keepsake",
        "priceUSD": 150,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Fine Sterling Silver",
        "stone": "Flush-Set Star Diamonds & Deep Blue Enamel",
        "purity": "925 Hallmarked",
        "cut": "Micro Round Cut",
        "clarity": "VVS1",
        "dimensions": "18mm Medallion Disc",
        "certificate": "Jewelux Seal",
        "description": "Celestial celestial dome featuring hand-drilled constellation stars filled with brilliant diamonds against satin-brushed silver.",
        "badge": "Personalized",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Gifts"
    },
    {
        "id": "HJ-NCK-008",
        "name": "The Royal Sapphire Halo Duchess Necklace",
        "category": "necklaces",
        "collection": "gold-vault",
        "tag": "Royal Sapphire",
        "priceUSD": 395,
        "image": "images/jewelux_hero_necklace.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K White Gold Finish on 925 Silver",
        "stone": "3.5ct Royal Ceylon Blue Sapphire with Halo",
        "purity": "925 Core 18K White Finish",
        "cut": "Oval Brilliant Facet",
        "clarity": "Deep Royal Blue Eye-Clean",
        "dimensions": "10x8mm Sapphire \u2022 18 inch Chain",
        "certificate": "GIA Certified Gemstone Dossier",
        "description": "Velvety midnight blue sapphire radiating regal poise, encircled by a scintillation halo of micropav\u00e9 diamonds.",
        "badge": "Royal Edit",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women"
    },
    {
        "id": "HJ-NCK-009",
        "name": "The Sovereign Bar Monogram Medallion",
        "category": "necklaces",
        "collection": "eternal-couples",
        "tag": "Couple Monogram",
        "priceUSD": 170,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Solid Sterling Silver",
        "stone": "Twin Diamond Bezel Points",
        "purity": "Solid 925 Stamped",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "30x6mm Heavy Bar",
        "certificate": "Jewelux Atelier Inscription",
        "description": "Sleek architectural silver ingot hand-inscribed with couple initials or milestone dates. Weighted luxury feel.",
        "badge": "Bespoke Engraved",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Couples & Men"
    },
    {
        "id": "HJ-NCK-010",
        "name": "The Florence Baroque Pearl & Gold Link Collar",
        "category": "necklaces",
        "collection": "gold-vault",
        "tag": "Baroque Statement",
        "priceUSD": 320,
        "image": "images/jewelux_editorial_hero.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Champagne Gold Vermeil & 925 Silver",
        "stone": "Sculptural Freshwater Baroque Pearl Centerpiece",
        "purity": "18K Vermeil over 925 Silver",
        "cut": "Organic Baroque Pearl & Pav\u00e9 Ring",
        "clarity": "Luminous Mirror Orient",
        "dimensions": "16 inch Paperclip Links \u2022 22mm Pearl",
        "certificate": "Pearl Dossier",
        "description": "Each organic baroque pearl is unique, hung from hand-assembled paperclip oval links finished in champagne gold.",
        "badge": "Runway Pick",
        "isSilver": true,
        "isGold": true,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Fashion Forward Women"
    },
    {
        "id": "HJ-BRO-001",
        "name": "The Sovereign Crest Royal Falcon Brooch",
        "category": "brooches",
        "collection": "silver-edit",
        "tag": "Haute Brooch",
        "priceUSD": 290,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_editorial_hero.jpg",
        "metal": "925 Fine Sterling Silver & Liquid Rhodium",
        "stone": "Baguette Cut Wing Feathers & Ruby Eye Accent",
        "purity": "Stamped 925 Hallmarked",
        "cut": "Step Cut Baguettes & Micro-Pav\u00e9",
        "clarity": "VVS1",
        "dimensions": "48mm Wingspan \u2022 Dual Locking Pin Clasp",
        "certificate": "Jewelux Atelier Masterpiece Dossier",
        "description": "A magnificent falcon in mid-descent. Baguette-cut diamonds form plumage edges while the eye glints with an intense pigeon-blood ruby.",
        "badge": "Signature Brooch",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Collectors & Haute Couturiers"
    },
    {
        "id": "HJ-BRO-002",
        "name": "The Florentine Lily Diamond Lapel Pin",
        "category": "brooches",
        "collection": "gold-vault",
        "tag": "Florentine Pin",
        "priceUSD": 210,
        "image": "images/jewelux_editorial_hero.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "18K Champagne Gold Finish on 925 Silver",
        "stone": "Pav\u00e9 Diamond Petals with Dewdrop Moissanite",
        "purity": "18K Vermeil over 925",
        "cut": "Round Brilliant Pav\u00e9",
        "clarity": "VVS1",
        "dimensions": "32mm Height",
        "certificate": "Jewelux Atelier Assurance",
        "description": "The regal heraldic fleur-de-lis of Florence sculpted in warm champagne gold, encrusted with brilliant pav\u00e9 diamonds.",
        "badge": "Heritage Lapel",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Men"
    },
    {
        "id": "HJ-BRO-003",
        "name": "The Celestial Crescent Moon & Star Brooch",
        "category": "brooches",
        "collection": "silver-edit",
        "tag": "Celestial Brooch",
        "priceUSD": 185,
        "image": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver (Platinum Sheen)",
        "stone": "Graduated Moissanites on Crescent Arc",
        "purity": "Stamped 925",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "36mm Diameter",
        "certificate": "GRA Verification",
        "description": "A poetic crescent moon sheltering a suspended starlight diamond. Designed to adorn silk scarves, tuxedo lapels, or evening capes.",
        "badge": "Editorial Favorite",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Connoisseurs"
    },
    {
        "id": "HJ-BRO-004",
        "name": "The Royal Peacock Feather Emerald Brooch",
        "category": "brooches",
        "collection": "temple-heritage",
        "tag": "Verdant Peacock",
        "priceUSD": 360,
        "image": "images/jewelux_temple_heritage.jpg",
        "hoverImage": "images/jewelux_hero_necklace.jpg",
        "metal": "22K Matte Gold Wash over 925 Silver",
        "stone": "Central Colombian Emerald with Blue Sapphire Eye",
        "purity": "925 Silver Core 22K Gold Finish",
        "cut": "Cabochon Emerald & Brilliant Pav\u00e9",
        "clarity": "Deep Vivid Hue",
        "dimensions": "55mm Length",
        "certificate": "Heritage Dossier",
        "description": "Capturing the sacred national emblem of India. Detailed filigree feathers bloom outward from a vivid royal green emerald center.",
        "badge": "Heirloom Edition",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Festive & Bridal"
    },
    {
        "id": "HJ-BRO-005",
        "name": "The Art Deco Geometric Sunburst Brooch",
        "category": "brooches",
        "collection": "silver-edit",
        "tag": "Art Deco Sunburst",
        "priceUSD": 240,
        "image": "images/jewelux_solitaire_ring.jpg",
        "hoverImage": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "metal": "925 Sterling Silver (Mirror Rhodium)",
        "stone": "Faceted Baguettes in Radial Arrangement",
        "purity": "Stamped 925",
        "cut": "Step Cut Baguettes",
        "clarity": "VVS1",
        "dimensions": "40mm Symmetrical Brooch",
        "certificate": "Jewelux Certificate",
        "description": "Sun rays of step-cut crystal facets bursting from an octagonal center. Pure 1920s Paris salon luxury.",
        "badge": "Vintage Revival",
        "isSilver": true,
        "isGold": false,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Art Deco Admirers"
    },
    {
        "id": "HJ-BRO-006",
        "name": "The Bridal Ribbon Corsage Brooch Pin",
        "category": "brooches",
        "collection": "eternal-couples",
        "tag": "Bridal Ribbon",
        "priceUSD": 195,
        "image": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_editorial_hero.jpg",
        "metal": "925 Sterling Silver with Liquid Platinum",
        "stone": "Fluid Pav\u00e9 Ribbon Bow with South Sea Pearl Drop",
        "purity": "925 Hallmarked",
        "cut": "Pav\u00e9 & AAA Pearl",
        "clarity": "VVS1",
        "dimensions": "38mm Width \u2022 10mm Pearl Drop",
        "certificate": "Bridal Atelier Dossier",
        "description": "Sensuously tied silken bow sculpted in silver, carrying a suspended glowing pearl. Ideal for bridal bouquets or silk sashes.",
        "badge": "Bridal Icon",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Brides"
    },
    {
        "id": "HJ-BRO-007",
        "name": "The Golden Palm Leaf Statement Pin",
        "category": "brooches",
        "collection": "gold-vault",
        "tag": "Botanical Haute",
        "priceUSD": 230,
        "image": "images/jewelux_editorial_hero.jpg",
        "hoverImage": "images/jewelux_hero_necklace.jpg",
        "metal": "18K Champagne Gold Vermeil on 925 Silver",
        "stone": "Micro-Pav\u00e9 Vein Accents",
        "purity": "18K Gold Finish 925",
        "cut": "Micro Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "50mm Linear Frond",
        "certificate": "Jewelux Seal",
        "description": "Organic palm frond with hand-hammered texture along each leaf, bisected by a brilliant row of micro-pav\u00e9 diamonds.",
        "badge": "Botanical",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Women & Men"
    },
    {
        "id": "HJ-BRO-008",
        "name": "The Dragonfly Luminary Pav\u00e9 Brooch",
        "category": "brooches",
        "collection": "silver-edit",
        "tag": "Filigree Creature",
        "priceUSD": 265,
        "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=85",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "925 Sterling Silver (Anti-Tarnish Rhodium)",
        "stone": "Filigree Wings Inset with Lab Diamonds & Sapphires",
        "purity": "Stamped 925",
        "cut": "Faceted Marquise & Round",
        "clarity": "VVS1",
        "dimensions": "44mm Wingspan",
        "certificate": "GRA Laboratory Certificate",
        "description": "Symbol of spiritual transformation. Openwork filigree wings catch backlighting with translucent diamond-bright clarity.",
        "badge": "Collector Piece",
        "isSilver": true,
        "isGold": false,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Jewelry Collectors"
    },
    {
        "id": "HJ-BRO-009",
        "name": "The Monarch Butterfly Basra Pearl Brooch",
        "category": "brooches",
        "collection": "temple-heritage",
        "tag": "Pearl Butterfly",
        "priceUSD": 310,
        "image": "images/jewelux_temple_heritage.jpg",
        "hoverImage": "images/jewelux_editorial_hero.jpg",
        "metal": "18K Gold Wash & 925 Sterling Silver",
        "stone": "Natural Teardrop Pearl Body & Pav\u00e9 Wings",
        "purity": "925 Core 18K Finish",
        "cut": "Natural Organic Pearl & Pav\u00e9",
        "clarity": "High Luster",
        "dimensions": "40mm Width",
        "certificate": "Pearl & Gem Dossier",
        "description": "Opulent monarch wings carved with micro-pav\u00e9 veins framing an incandescent genuine natural pearl thorax.",
        "badge": "Exquisite",
        "isSilver": true,
        "isGold": true,
        "isNew": false,
        "stockStatus": "In Stock",
        "targetAudience": "Elegance Lovers"
    },
    {
        "id": "HJ-BRO-010",
        "name": "The Minimalist Architectural Gold Quill Pin",
        "category": "brooches",
        "collection": "gold-vault",
        "tag": "Sartorial Quill",
        "priceUSD": 175,
        "image": "images/jewelux_editorial_hero.jpg",
        "hoverImage": "images/jewelux_solitaire_ring.jpg",
        "metal": "18K Champagne Gold Finish on 925 Silver",
        "stone": "Solitaire Diamond Nib Point",
        "purity": "Solid 925 Core",
        "cut": "Round Brilliant",
        "clarity": "VVS1",
        "dimensions": "58mm Sleek Quill Pin",
        "certificate": "Jewelux Seal",
        "description": "Sleek Didone feather quill celebrating literature and diplomacy. Designed with an ultra-fine safety pin mechanism for fine fabrics.",
        "badge": "Sartorial Minimal",
        "isSilver": true,
        "isGold": true,
        "isNew": true,
        "stockStatus": "In Stock",
        "targetAudience": "Sartorial Gentlemen & Women"
    }
],

  policies: {
    shipping: "Complimentary armored white-glove transport on all orders over $250 / ₹20,000. All shipments are 100% insured from our atelier doors to your hands. Standard delivery takes 2–4 business days domestically and 4–7 business days globally.",
    returns: "We offer an unconditional 30-day return guarantee. If your piece does not evoke absolute wonder upon opening the jewel box, contact our WhatsApp Concierge for complimentary insured pickup and a 100% full refund.",
    authenticity: "Zero fake claims covenant: Every piece is accompanied by stamped hallmarking (925 for silver, BIS 750/916 for gold) and independent gemological dossiers (GRA / GIA / IGI). We never use base metals or faux plastic stones."
  },

  bespokeStudio: {
    metals: [
      { id: 'liquid-silver', name: '925 Platinum-Rhodium Silver', color: '#E8EBF0', specular: '#FFFFFF', priceBase: 180, isSilver: true },
      { id: 'champagne-gold', name: '18K Florentine Champagne Gold', color: '#DECCA8', specular: '#FFF8EC', priceBase: 2400, isSilver: false },
      { id: 'rose-gold', name: '18K Venetian Rose Gold', color: '#E5B299', specular: '#FFEAE0', priceBase: 2400, isSilver: false },
      { id: 'platinum', name: 'Pure Platinum 950', color: '#D9DDE2', specular: '#FFFFFF', priceBase: 3100, isSilver: false }
    ],
    gems: [
      { id: 'moissanite', name: 'D-Flawless Lab Moissanite', color: '#FFFFFF', dispersion: 0.104, pricePerCarat: 75 },
      { id: 'diamond', name: 'D-Flawless Natural Diamond (GIA)', color: '#FFFFFF', dispersion: 0.044, pricePerCarat: 4800 },
      { id: 'emerald', name: 'Muzo Colombian Emerald', color: '#10B981', dispersion: 0.014, pricePerCarat: 3200 },
      { id: 'sapphire', name: 'Ceylon Royal Sapphire', color: '#1D4ED8', dispersion: 0.018, pricePerCarat: 2800 },
      { id: 'ruby', name: 'Burmese Pigeon Blood Ruby', color: '#BE123C', dispersion: 0.018, pricePerCarat: 3900 }
    ],
    cuts: [
      { id: 'round', name: 'Round Brilliant', ratio: 1.0 },
      { id: 'princess', name: 'Princess', ratio: 1.0 },
      { id: 'oval', name: 'Oval', ratio: 1.08 },
      { id: 'emerald-cut', name: 'Emerald Cut', ratio: 1.15 },
      { id: 'radiant', name: 'Radiant Cut', ratio: 1.14 },
      { id: 'heart', name: 'Heart', ratio: 1.10 },
      { id: 'asscher', name: 'Asscher Cut', ratio: 1.05 },
      { id: 'marquise', name: 'Marquise', ratio: 1.20 },
      { id: 'pear', name: 'Pear / Teardrop', ratio: 1.12 },
      { id: 'cushion', name: 'Cushion', ratio: 1.06 },
      { id: 'elongated-cushion', name: 'Elongated Cushion', ratio: 1.12 },
      { id: 'hexagonal', name: 'Hexagonal', ratio: 1.10 }
    ],
    carats: [
      { weight: 1.0, label: '1.00 Carat' },
      { weight: 1.75, label: '1.75 Carat' },
      { weight: 2.5, label: '2.50 Carat (Flagship)' },
      { weight: 4.0, label: '4.00 Carat (Statement)' }
    ]
  }
};

// ================= MULTILINGUAL DICTIONARY (INTERNATIONAL READY) =================
const JEWELUX_I18N = {
  en: {
    announcement: "THE SILVER EDIT 2026 — 925 Hallmarked Fine Silver & Anti-Tarnish Rhodium • Complimentary Insured Delivery",
    nav_all: "All Masterpieces",
    nav_silver: "Fine 925 Silver",
    nav_couples: "Newlywed & Couples",
    nav_gold: "The Gold Vault",
    nav_craftsmanship: "Craftsmanship",
    nav_about: "About Us",
    nav_bespoke: "Bespoke 3D Studio",
    nav_studio: "Founder Studio",
    cta_add_bag: "Add to Bag",
    cta_acquire_now: "Acquire Now",
    cta_whatsapp: "Inquire on WhatsApp",
    cta_consult: "Consult Atelier",
    purity_silver: "925 Hallmarked Fine Silver",
    purity_gold: "18K/22K BIS Hallmarked Gold",
    badge_silver_spotlight: "Silver Spotlight",
    honest_luxury_title: "The Honest Luxury Covenant",
    honest_luxury_desc: "100% Certified 925 Sterling Silver & BIS Hallmarked Gold. Zero fake claims, verified gemological dossiers, and lifetime complimentary cleaning."
  },
  hi: {
    announcement: "द सिल्वर एडिट 2026 — 925 हॉलमार्क फाइन सिल्वर और एंटी-टार्निश रोडियम • मुफ़्त बीमाकृत डिलीवरी",
    nav_all: "सभी गहने",
    nav_silver: "फाइन 925 सिल्वर",
    nav_couples: "नवविवाहित और कपल्स",
    nav_gold: "रॉयल गोल्ड वॉल्ट",
    nav_craftsmanship: "कारीगरी",
    nav_about: "हमारे बारे में",
    nav_bespoke: "3D रिंग स्टूडियो",
    nav_studio: "फाउंडर स्टूडियो",
    cta_add_bag: "बैग में जोड़ें",
    cta_acquire_now: "अभी खरीदें",
    cta_whatsapp: "व्हाट्सएप पर बात करें",
    cta_consult: "कारीगर से सलाह लें",
    purity_silver: "925 हॉलमार्क्ड शुद्ध चांदी",
    purity_gold: "18K/22K बीआईएस हॉलमार्क सोना",
    badge_silver_spotlight: "सिल्वर स्पॉटलाइट",
    honest_luxury_title: "सच्ची लग्ज़री का वादा",
    honest_luxury_desc: "100% प्रमाणित 925 स्टर्लिंग चांदी और बीआईएस हॉलमार्क सोना। कोई झूठे दावे नहीं, प्रामाणिक लैब सर्टिफिकेट और आजीवन मुफ़्त पॉलिशिंग।"
  },
  fr: {
    announcement: "L'ÉDITION ARGENT 2026 — Argent 925 Poinçonné et Rhodium Anti-Ternissure • Livraison Offerte et Assurée",
    nav_all: "Toutes les Pièces",
    nav_silver: "Argent Fin 925",
    nav_couples: "Nouveaux Mariés & Couples",
    nav_gold: "Le Coffre d'Or",
    nav_craftsmanship: "Savoir-Faire",
    nav_about: "Maison",
    nav_bespoke: "Studio 3D Sur-Mesure",
    nav_studio: "Studio Fondateur",
    cta_add_bag: "Ajouter au Panier",
    cta_acquire_now: "Acquérir",
    cta_whatsapp: "Consulter sur WhatsApp",
    cta_consult: "Prendre Rendez-vous",
    purity_silver: "Argent 925 Poinçonné",
    purity_gold: "Or 18K/22K Certifié",
    badge_silver_spotlight: "Vedette Argent",
    honest_luxury_title: "Le Pacte de Luxe Véritable",
    honest_luxury_desc: "Argent 925 pur et Or certifié. Aucune fausse promesse, rapports gemmologiques rigoureux et garantie à vie."
  },
  it: {
    announcement: "THE SILVER EDIT 2026 — Argento 925 Punzonato e Rodio Lucido • Consegna Assicurata Gratuita",
    nav_all: "Tutti i Capolavori",
    nav_silver: "Argento 925 Pregiato",
    nav_couples: "Sposi & Coppie",
    nav_gold: "Il Caveau d'Oro",
    nav_craftsmanship: "Artigianato",
    nav_about: "La Maison",
    nav_bespoke: "Studio 3D su Misura",
    nav_studio: "Studio Fondatore",
    cta_add_bag: "Aggiungi al Carrello",
    cta_acquire_now: "Acquista Ora",
    cta_whatsapp: "Contatta su WhatsApp",
    cta_consult: "Consulta l'Atelier",
    purity_silver: "Argento 925 Autentico",
    purity_gold: "Oro 18K/22K Certificato",
    badge_silver_spotlight: "In Primo Piano",
    honest_luxury_title: "Il Patto del Lusso Autentico",
    honest_luxury_desc: "Argento 925 e Oro garantito al 100%. Trasparenza assoluta, certificati gemmologici e cura a vita."
  }
};

// ================= STORAGE & PERSISTENCE HELPER (NO CODE EDITING NEEDED) =================
const JEWELUX_STORAGE = {
  KEY: 'jewelux_custom_data_v2',

  getStoreData() {
    try {
      const saved = localStorage.getItem(this.KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        return {
          ...JEWELUX_DATA,
          storeConfig: { ...JEWELUX_DATA.storeConfig, ...(parsed.storeConfig || {}) },
          products: parsed.products && parsed.products.length ? parsed.products : JEWELUX_DATA.products,
          faqs: parsed.faqs && parsed.faqs.length ? parsed.faqs : JEWELUX_DATA.faqs,
          policies: { ...JEWELUX_DATA.policies, ...(parsed.policies || {}) },
          inquiries: parsed.inquiries || []
        };
      }
    } catch (e) {
      console.warn('Could not read custom store data from localStorage', e);
    }
    return { ...JEWELUX_DATA, inquiries: [] };
  },

  saveStoreData(customData) {
    try {
      localStorage.setItem(this.KEY, JSON.stringify(customData));
      return true;
    } catch (e) {
      console.error('Error saving store data to localStorage', e);
      return false;
    }
  },

  exportJson() {
    const data = this.getStoreData();
    const str = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(data, null, 2));
    const dlAnchor = document.createElement('a');
    dlAnchor.setAttribute("href", str);
    dlAnchor.setAttribute("download", `house-of-jewelux-backup-${new Date().toISOString().slice(0,10)}.json`);
    document.body.appendChild(dlAnchor);
    dlAnchor.click();
    dlAnchor.remove();
  },

  importJson(jsonString) {
    try {
      const parsed = JSON.parse(jsonString);
      if (parsed && (parsed.products || parsed.storeConfig)) {
        this.saveStoreData(parsed);
        return true;
      }
    } catch (e) {
      console.error('Invalid JSON file', e);
    }
    return false;
  },

  resetDefaults() {
    localStorage.removeItem(this.KEY);
  }
};

if (typeof window !== 'undefined') {
  window.JEWELUX_DATA = JEWELUX_DATA;
  window.JEWELUX_I18N = JEWELUX_I18N;
  window.JEWELUX_STORAGE = JEWELUX_STORAGE;
}
